// pages/Playbook.jsx
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import PlaybookCard from '../components/PlaybookCard';
import { useTheme } from '../context/Themecontext';

const Playbook = () => {
  const { isDark } = useTheme();

  const [playbookActions, setPlaybookActions] = useState({
    staffing: [],
    supplies: [],
    advisories: []
  });
  const [metadata, setMetadata] = useState({
    reason_for_surge: '',
    raw_prediction_summary: null,
    generated_at: null,
  });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    fetchPlaybook();
  }, []);

  const fetchPlaybook = async () => {
    setLoading(true);
    setError('');
    try {
      const response = await axios.post('http://127.0.0.1:6969/agent', {
        horizon: '1d',
        location: 'Mumbai'
      });

      if (!response.data.ok) {
        throw new Error(response.data.error || 'Failed to fetch playbook');
      }

      const plan = response.data.agent_plan;

      setPlaybookActions({
        staffing: plan.staffing || [],
        supplies: plan.supplies || [],
        advisories: plan.advisories || [],
      });

      setMetadata({
        reason_for_surge: plan.reason_for_surge || 'No specific trigger identified',
        raw_prediction_summary: plan.raw_prediction_summary || null,
        generated_at: new Date(),
      });
    } catch (err) {
      setError(err.message || 'Failed to load playbook');
    } finally {
      setLoading(false);
    }
  };

  // Calculate summary stats
  const totalActions = playbookActions.staffing.length + playbookActions.supplies.length + playbookActions.advisories.length;
  const completedActions = [...playbookActions.staffing, ...playbookActions.supplies, ...playbookActions.advisories].filter(a => a.status === 'completed').length;
  const inProgressActions = [...playbookActions.staffing, ...playbookActions.supplies, ...playbookActions.advisories].filter(a => a.status === 'in-progress').length;
  const pendingActions = [...playbookActions.staffing, ...playbookActions.supplies, ...playbookActions.advisories].filter(a => a.status === 'pending').length;

  if (loading) {
    return (
      <div className="flex items-center justify-center h-screen">
        <div className="text-center">
          <div className="animate-spin rounded-full h-16 w-16 border-b-2 border-blue-600 mx-auto mb-4"></div>
          <p className={`text-lg ${isDark ? 'text-gray-300' : 'text-gray-700'}`}>
            AI Agent generating playbook...
          </p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex items-center justify-center h-screen">
        <div className={`p-6 rounded-lg border ${isDark ? 'bg-red-900 border-red-700' : 'bg-red-50 border-red-200'}`}>
          <p className={`text-lg font-semibold ${isDark ? 'text-red-200' : 'text-red-700'}`}>
            Error: {error}
          </p>
          <button
            onClick={fetchPlaybook}
            className="mt-4 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg"
          >
            Retry
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className={`text-3xl font-bold transition-colors ${
            isDark ? 'text-white' : 'text-gray-800'
          }`}>
            AI Surge Response Playbook
          </h1>
          <p className={`transition-colors ${
            isDark ? 'text-gray-400' : 'text-gray-600'
          }`}>
            Automated action plan generated by Gemini AI agent
          </p>
        </div>
        <button className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-lg font-semibold transition-colors flex items-center space-x-2">
          <span>📄</span>
          <span>Export as PDF</span>
        </button>
      </div>

      {/* Playbook Generated Info */}
      <div className="bg-gradient-to-r from-blue-500 to-purple-600 text-white rounded-xl p-6">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-xl font-bold mb-2">Playbook Generated Successfully! 🎯</h2>
            <p className="opacity-90">AI agent has analyzed current conditions and prepared optimized response actions</p>
          </div>
          <div className="text-right">
            <p className="text-sm opacity-90">Generated: {metadata.generated_at?.toLocaleString()}</p>
            <p className="text-sm opacity-90">
              Horizon: {metadata.raw_prediction_summary?.horizon || 'N/A'}
            </p>
          </div>
        </div>
      </div>

      {/* Reason for Surge */}
      <div className={`rounded-xl shadow-sm border p-6 transition-colors ${
        isDark ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-200'
      }`}>
        <div className="flex items-start space-x-3">
          <div className={`p-3 rounded-lg transition-colors ${
            isDark ? 'bg-yellow-900' : 'bg-yellow-100'
          }`}>
            <span className="text-2xl">⚠️</span>
          </div>
          <div className="flex-1">
            <h3 className={`text-lg font-semibold mb-2 transition-colors ${
              isDark ? 'text-white' : 'text-gray-800'
            }`}>
              Predicted Surge Trigger
            </h3>
            <p className={`transition-colors ${
              isDark ? 'text-gray-300' : 'text-gray-700'
            }`}>
              {metadata.reason_for_surge}
            </p>
            {metadata.raw_prediction_summary && (
              <div className="mt-4 grid grid-cols-2 md:grid-cols-4 gap-3">
                <div className={`p-3 rounded-lg ${isDark ? 'bg-gray-700' : 'bg-gray-50'}`}>
                  <div className={`text-xs ${isDark ? 'text-gray-400' : 'text-gray-600'}`}>Total Admissions</div>
                  <div className={`text-lg font-bold ${isDark ? 'text-white' : 'text-gray-800'}`}>
                    {metadata.raw_prediction_summary.total_predicted_admissions?.toFixed(0)}
                  </div>
                </div>
                <div className={`p-3 rounded-lg ${isDark ? 'bg-gray-700' : 'bg-gray-50'}`}>
                  <div className={`text-xs ${isDark ? 'text-gray-400' : 'text-gray-600'}`}>Peak Load</div>
                  <div className={`text-lg font-bold ${isDark ? 'text-white' : 'text-gray-800'}`}>
                    {metadata.raw_prediction_summary.peak_admissions?.toFixed(1)}
                  </div>
                </div>
                <div className={`p-3 rounded-lg ${isDark ? 'bg-gray-700' : 'bg-gray-50'}`}>
                  <div className={`text-xs ${isDark ? 'text-gray-400' : 'text-gray-600'}`}>Avg/Hour</div>
                  <div className={`text-lg font-bold ${isDark ? 'text-white' : 'text-gray-800'}`}>
                    {metadata.raw_prediction_summary.avg_hourly_admissions?.toFixed(1)}
                  </div>
                </div>
                <div className={`p-3 rounded-lg ${isDark ? 'bg-gray-700' : 'bg-gray-50'}`}>
                  <div className={`text-xs ${isDark ? 'text-gray-400' : 'text-gray-600'}`}>Peak Time</div>
                  <div className={`text-sm font-bold ${isDark ? 'text-white' : 'text-gray-800'}`}>
                    {metadata.raw_prediction_summary.peak_timestamp ? new Date(metadata.raw_prediction_summary.peak_timestamp).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }) : 'N/A'}
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Action Categories */}
      <div className="space-y-8">
        {/* Staffing Actions */}
        <div>
          <div className="flex items-center space-x-3 mb-4">
            <div className={`p-3 rounded-lg transition-colors ${
              isDark ? 'bg-green-900' : 'bg-green-100'
            }`}>
              <span className="text-2xl">👥</span>
            </div>
            <div>
              <h2 className={`text-2xl font-bold transition-colors ${
                isDark ? 'text-white' : 'text-gray-800'
              }`}>
                Staffing Recommendations
              </h2>
              <p className={`transition-colors ${
                isDark ? 'text-gray-400' : 'text-gray-600'
              }`}>
                Optimize medical staff allocation and scheduling
              </p>
            </div>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {playbookActions.staffing.length > 0 ? (
              playbookActions.staffing.map(action => (
                <PlaybookCard key={action.id} {...action} />
              ))
            ) : (
              <p className={`col-span-3 text-center py-8 ${isDark ? 'text-gray-400' : 'text-gray-500'}`}>
                No staffing actions recommended
              </p>
            )}
          </div>
        </div>

        {/* Supply Actions */}
        <div>
          <div className="flex items-center space-x-3 mb-4">
            <div className={`p-3 rounded-lg transition-colors ${
              isDark ? 'bg-orange-900' : 'bg-orange-100'
            }`}>
              <span className="text-2xl">📦</span>
            </div>
            <div>
              <h2 className={`text-2xl font-bold transition-colors ${
                isDark ? 'text-white' : 'text-gray-800'
              }`}>
                Supply Chain Actions
              </h2>
              <p className={`transition-colors ${
                isDark ? 'text-gray-400' : 'text-gray-600'
              }`}>
                Manage medical supplies and equipment inventory
              </p>
            </div>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {playbookActions.supplies.length > 0 ? (
              playbookActions.supplies.map(action => (
                <PlaybookCard key={action.id} {...action} />
              ))
            ) : (
              <p className={`col-span-3 text-center py-8 ${isDark ? 'text-gray-400' : 'text-gray-500'}`}>
                No supply actions recommended
              </p>
            )}
          </div>
        </div>

        {/* Advisory Actions */}
        <div>
          <div className="flex items-center space-x-3 mb-4">
            <div className={`p-3 rounded-lg transition-colors ${
              isDark ? 'bg-blue-900' : 'bg-blue-100'
            }`}>
              <span className="text-2xl">📢</span>
            </div>
            <div>
              <h2 className={`text-2xl font-bold transition-colors ${
                isDark ? 'text-white' : 'text-gray-800'
              }`}>
                Patient Advisories
              </h2>
              <p className={`transition-colors ${
                isDark ? 'text-gray-400' : 'text-gray-600'
              }`}>
                Public health communications and alerts
              </p>
            </div>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {playbookActions.advisories.length > 0 ? (
              playbookActions.advisories.map(action => (
                <PlaybookCard key={action.id} {...action} />
              ))
            ) : (
              <p className={`col-span-3 text-center py-8 ${isDark ? 'text-gray-400' : 'text-gray-500'}`}>
                No advisories recommended
              </p>
            )}
          </div>
        </div>
      </div>

      {/* Playbook Summary */}
      <div className={`rounded-xl shadow-sm border p-6 transition-colors ${
        isDark ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-200'
      }`}>
        <h3 className={`text-lg font-semibold mb-4 transition-colors ${
          isDark ? 'text-white' : 'text-gray-800'
        }`}>
          Playbook Summary
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <div className={`p-4 rounded-lg text-center transition-colors ${
            isDark ? 'bg-blue-900' : 'bg-blue-50'
          }`}>
            <div className={`text-2xl font-bold transition-colors ${
              isDark ? 'text-blue-300' : 'text-blue-600'
            }`}>
              {totalActions}
            </div>
            <div className={`text-sm transition-colors ${
              isDark ? 'text-blue-200' : 'text-blue-700'
            }`}>
              Total Actions
            </div>
          </div>
          <div className={`p-4 rounded-lg text-center transition-colors ${
            isDark ? 'bg-green-900' : 'bg-green-50'
          }`}>
            <div className={`text-2xl font-bold transition-colors ${
              isDark ? 'text-green-300' : 'text-green-600'
            }`}>
              {completedActions}
            </div>
            <div className={`text-sm transition-colors ${
              isDark ? 'text-green-200' : 'text-green-700'
            }`}>
              Completed
            </div>
          </div>
          <div className={`p-4 rounded-lg text-center transition-colors ${
            isDark ? 'bg-yellow-900' : 'bg-yellow-50'
          }`}>
            <div className={`text-2xl font-bold transition-colors ${
              isDark ? 'text-yellow-300' : 'text-yellow-600'
            }`}>
              {inProgressActions}
            </div>
            <div className={`text-sm transition-colors ${
              isDark ? 'text-yellow-200' : 'text-yellow-700'
            }`}>
              In Progress
            </div>
          </div>
          <div className={`p-4 rounded-lg text-center transition-colors ${
            isDark ? 'bg-gray-700' : 'bg-gray-50'
          }`}>
            <div className={`text-2xl font-bold transition-colors ${
              isDark ? 'text-gray-300' : 'text-gray-600'
            }`}>
              {pendingActions}
            </div>
            <div className={`text-sm transition-colors ${
              isDark ? 'text-gray-200' : 'text-gray-700'
            }`}>
              Pending
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Playbook;
